### ISSUE TITLE
show other players in the game

### ISSUE THREAD

**Issue by trasa** [DigiPen-Network-Classes/ScaryCaves#3]
using redis and pub sub add player presence to the game:
* `Bob is standing here.`
* `Bob attacks a rat!`
* `The rat hits Bob!`

that means sanitising usernames and making it so you cant just spam "bad words / hate speech" etc.
and that's difficult to do for real.

**Comment by trasa-manticore** [comment]
Fixed!

**Comment by trasa** [comment]
Implemented; notifications happen now.
